'use client'

import { Check, Link, Save, Trash2 } from 'lucide-react'
import type { SavedConfiguration } from '@/lib/saved-configurations'

type Props = { configurations: SavedConfiguration[]; activeId: string; sharedName: string; shareStatus: 'idle' | 'copied'; onLoad: (id: string) => void; onSave: () => void; onShare: () => void; onDelete: () => void }

export function SavedConfigurations({ configurations, activeId, sharedName, shareStatus, onLoad, onSave, onShare, onDelete }: Props) {
  return <section className="mb-6 rounded-2xl border border-slate-200 bg-white/90 p-4 shadow-sm sm:flex sm:items-center sm:gap-4 sm:p-5" aria-labelledby="saved-configurations-title">
    <div className="mb-3 flex items-start gap-3 sm:mb-0 sm:min-w-0 sm:flex-1"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#eef7f5] text-[#12604f]"><Save size={18} /></div><div><h2 id="saved-configurations-title" className="text-sm font-bold text-[#103c52]">Saved site configurations</h2><p className="mt-1 text-xs text-slate-500">Keep separate areas and bid prices ready for your next auction.</p>{sharedName ? <p className="mt-2 inline-flex max-w-full items-center rounded-full border border-[#bfe2d8] bg-[#f1faf7] px-2.5 py-1 text-[11px] font-semibold text-[#12604f]">Shared site: <span className="ml-1 truncate">{sharedName}</span></p> : null}</div></div>
    <div className="flex flex-col gap-2 sm:flex-row sm:items-center"><label htmlFor="saved-configuration" className="sr-only">Choose a saved site configuration</label><select id="saved-configuration" value={activeId} onChange={event => onLoad(event.currentTarget.value)} className="h-11 min-w-0 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-medium text-slate-700 outline-none transition focus:border-[#e68a4a] focus:ring-4 focus:ring-orange-100 sm:min-w-52"><option value="">Choose a saved site</option>{configurations.map(configuration => <option key={configuration.id} value={configuration.id}>{configuration.name}</option>)}</select><div className="flex flex-wrap gap-2"><button type="button" onClick={onSave} className="flex h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-[#103c52] px-4 text-sm font-semibold text-white transition hover:bg-[#164c65] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-100 sm:flex-none"><Save size={15} /> Save current</button><button type="button" onClick={onShare} className="flex h-11 flex-1 items-center justify-center gap-2 rounded-xl border border-[#bfe2d8] bg-[#f1faf7] px-4 text-sm font-semibold text-[#12604f] transition hover:bg-[#e4f5ef] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-100 sm:flex-none">{shareStatus === 'copied' ? <Check size={15} /> : <Link size={15} />} {shareStatus === 'copied' ? 'Link copied' : 'Share link'}</button><button type="button" onClick={onDelete} disabled={!activeId} aria-label="Delete selected saved configuration" className="flex size-11 items-center justify-center rounded-xl border border-slate-200 text-slate-500 transition hover:border-red-200 hover:bg-red-50 hover:text-red-600 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-100 disabled:cursor-not-allowed disabled:opacity-40"><Trash2 size={16} /></button></div></div>
  </section>
}
